from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from io import BytesIO
from models import Visit, EMR, Patient, Doctor, DiseaseRisk

def generate_visit_pdf(visit: Visit, patient: Patient, doctor: Doctor, emr: EMR, risk: DiseaseRisk) -> BytesIO:
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=72, leftMargin=72, topMargin=72, bottomMargin=18)
    
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name='CenterTitle', parent=styles['Title'], alignment=TA_CENTER))
    
    story = []
    
    # --- Header ---
    if doctor.clinicName:
        story.append(Paragraph(doctor.clinicName, styles['CenterTitle']))
    story.append(Paragraph(f"Dr. {doctor.name}", styles['Heading2']))
    if doctor.phone:
        story.append(Paragraph(f"Phone: {doctor.phone}", styles['Normal']))
    story.append(Spacer(1, 12))
    story.append(Paragraph("_" * 60, styles['Normal'])) # Divider
    story.append(Spacer(1, 12))
    
    # --- Patient Info ---
    patient_data = [
        [f"Patient Name: {patient.name}", f"Date: {visit.visitDate.strftime('%Y-%m-%d')}"],
        [f"Age/Gender: {patient.age or 'N/A'} / {patient.gender or 'N/A'}", f"Visit ID: {visit.id[-8:]}"]
    ]
    if patient.abhaId:
        patient_data.append([f"ABHA ID: {patient.abhaId}", ""])
        
    t = Table(patient_data, colWidths=[300, 150])
    t.setStyle(TableStyle([
        ('FONTNAME', (0,0), (-1,-1), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(t)
    story.append(Spacer(1, 24))
    
    # --- EMR Sections ---
    def add_section(title, content):
        if content:
            story.append(Paragraph(title, styles['Heading3']))
            story.append(Paragraph(content, styles['Normal']))
            story.append(Spacer(1, 12))

    add_section("Chief Complaint", emr.chiefComplaint)
    add_section("History of Present Illness", emr.hpi)
    add_section("Past History", emr.pastHistory)
    add_section("Allergies", emr.allergies)
    
    if emr.medications:
        story.append(Paragraph("Medications", styles['Heading3']))
        for med in emr.medications:
            story.append(Paragraph(f"• {med}", styles['Normal']))
        story.append(Spacer(1, 12))
        
    add_section("Examination Findings", emr.examFindings)
    add_section("Diagnosis", emr.diagnosis)
    add_section("Plan / Instructions", emr.plan)
    
    if emr.followUpDays:
        add_section("Follow Up", f"Please visit again in {emr.followUpDays} days.")
        
    # --- Disease Risk Analysis (Internal Use / Optional on PDF) ---
    # Decided to include it as a note for the doctor/patient
    story.append(Spacer(1, 24))
    story.append(Paragraph("AI Risk Analysis", styles['Heading4']))
    risk_data = [
        ["Condition", "Probability"],
        ["Flu", f"{risk.fluProbability:.0%}"],
        ["Migraine", f"{risk.migraineProbability:.0%}"],
        ["Fatigue", f"{risk.fatigueProbability:.0%}"]
    ]
    t_risk = Table(risk_data, colWidths=[150, 100], hAlign='LEFT')
    t_risk.setStyle(TableStyle([
        ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
        ('BACKGROUND', (0,0), (1,0), colors.lightgrey),
    ]))
    story.append(t_risk)
    if risk.notes:
        story.append(Spacer(1, 6))
        story.append(Paragraph(f"Note: {risk.notes}", styles['Italic']))

    # --- Footer ---
    story.append(Spacer(1, 48))
    story.append(Paragraph("Generated by MediScribe", styles['Italic']))
    
    doc.build(story)
    buffer.seek(0)
    return buffer
